scheb_two_factor:
  security_tokens:
    - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

  totp:
    enabled: true
    server_name: '%accessing.product_name%'
    issuer: '%accessing.product_name%'
    leeway: 0
    template: security/2fa_form.html.twig
