scheb_two_factor:
  security_tokens:
    - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

  totp:
    enabled: true
    server_name: '%accessing.product_name%'
    issuer: '%accessing.product_name%'
    digits: 6
    period: 30
    algorithm: sha1
