<?php
# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260330174000 extends AbstractMigration
{
    /** @noinspection PhpMissingParentCallCommonInspection */
    public function getDescription(): string
    {
        return 'Create initial Accessing user, verification, recovery, and security event tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE access_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password_hash VARCHAR(255) NOT NULL, display_name VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(32) DEFAULT NULL, email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, phone_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, second_factor_enabled BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, failed_login_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_access_user_email ON access_user (email)');

        $this->addSql('CREATE TABLE access_security_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, event_type VARCHAR(64) NOT NULL, context JSON NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_access_security_event_type ON access_security_event (event_type)');
        $this->addSql('CREATE INDEX idx_access_security_event_occurred_at ON access_security_event (occurred_at)');
        $this->addSql('CREATE INDEX IDX_336C8ED99B6B5FBA ON access_security_event (user_id)');
        $this->addSql('ALTER TABLE access_security_event ADD CONSTRAINT FK_336C8ED99B6B5FBA FOREIGN KEY (user_id) REFERENCES access_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE access_verification_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, channel_type VARCHAR(32) NOT NULL, token VARCHAR(32) NOT NULL, target VARCHAR(255) NOT NULL, completed BOOLEAN NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_access_verification_challenge_type ON access_verification_challenge (channel_type)');
        $this->addSql('CREATE INDEX idx_access_verification_challenge_expires_at ON access_verification_challenge (expires_at)');
        $this->addSql('CREATE INDEX IDX_84BBA3B69B6B5FBA ON access_verification_challenge (user_id)');
        $this->addSql('ALTER TABLE access_verification_challenge ADD CONSTRAINT FK_84BBA3B69B6B5FBA FOREIGN KEY (user_id) REFERENCES access_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE access_recovery_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, code_hash VARCHAR(255) NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_access_recovery_code_consumed_at ON access_recovery_code (consumed_at)');
        $this->addSql('CREATE INDEX IDX_C330E4C89B6B5FBA ON access_recovery_code (user_id)');
        $this->addSql('ALTER TABLE access_recovery_code ADD CONSTRAINT FK_C330E4C89B6B5FBA FOREIGN KEY (user_id) REFERENCES access_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    /** @noinspection PhpMissingParentCallCommonInspection */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE access_security_event DROP CONSTRAINT FK_336C8ED99B6B5FBA');
        $this->addSql('ALTER TABLE access_verification_challenge DROP CONSTRAINT FK_84BBA3B69B6B5FBA');
        $this->addSql('ALTER TABLE access_recovery_code DROP CONSTRAINT FK_C330E4C89B6B5FBA');
        $this->addSql('DROP TABLE access_security_event');
        $this->addSql('DROP TABLE access_verification_challenge');
        $this->addSql('DROP TABLE access_recovery_code');
        $this->addSql('DROP TABLE access_user');
    }
}
