<?php
# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260330180500 extends AbstractMigration
{
    /** @noinspection PhpMissingParentCallCommonInspection */
    public function getDescription(): string
    {
        return 'Create Accessing account session and reset password request tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE accessing_account_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_id INT NOT NULL, session_identifier VARCHAR(128) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, trusted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACCESSING_ACCOUNT_SESSION_IDENTIFIER ON accessing_account_session (session_identifier)');
        $this->addSql('CREATE INDEX idx_accessing_account_session_expires_at ON accessing_account_session (expires_at)');
        $this->addSql('CREATE INDEX idx_accessing_account_session_revoked_at ON accessing_account_session (revoked_at)');
        $this->addSql('CREATE INDEX IDX_B5B768E39B6B5FBA ON accessing_account_session (account_id)');
        $this->addSql('ALTER TABLE accessing_account_session ADD CONSTRAINT FK_B5B768E39B6B5FBA FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE accessing_reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL COMMENT '(DC2Type:datetime_immutable)', expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL COMMENT '(DC2Type:datetime_immutable)', PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_C89A6A619B6B5FBA ON accessing_reset_password_request (account_id)');
        $this->addSql('CREATE INDEX IDX_C89A6A6168A9831C ON accessing_reset_password_request (selector)');
        $this->addSql('ALTER TABLE accessing_reset_password_request ADD CONSTRAINT FK_C89A6A619B6B5FBA FOREIGN KEY (account_id) REFERENCES accessing_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    /** @noinspection PhpMissingParentCallCommonInspection */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE accessing_account_session DROP CONSTRAINT FK_B5B768E39B6B5FBA');
        $this->addSql('ALTER TABLE accessing_reset_password_request DROP CONSTRAINT FK_C89A6A619B6B5FBA');
        $this->addSql('DROP TABLE accessing_account_session');
        $this->addSql('DROP TABLE accessing_reset_password_request');
    }
}
