<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260912003630 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Canonical Accessing PostgreSQL baseline generated from current Doctrine metadata.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Accessing data migrations require PostgreSQL.');
        $this->addSql('CREATE TABLE access_credential (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, password_hash VARCHAR(255) NOT NULL, password_changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F4185CAA76ED395 ON access_credential (user_id)');
        $this->addSql('CREATE TABLE access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, display_name VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(32) DEFAULT NULL, email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, phone_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked BOOLEAN NOT NULL, failed_login_count INT NOT NULL, locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_sign_in_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6692B54D17F50A6 ON access (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6692B54989D9B62 ON access (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_access_email ON access (email)');
        $this->addSql('CREATE TABLE access_external_identity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, email_verified BOOLEAN NOT NULL, display_name VARCHAR(255) DEFAULT NULL, avatar_url VARCHAR(2048) DEFAULT NULL, last_authenticated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, source VARCHAR(190) DEFAULT NULL, provider VARCHAR(190) DEFAULT NULL, external_id VARCHAR(190) DEFAULT NULL, source_type VARCHAR(120) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B5367E2D17F50A6 ON access_external_identity (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B5367E2989D9B62 ON access_external_identity (slug)');
        $this->addSql('CREATE INDEX idx_access_external_identity_user ON access_external_identity (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_access_external_identity_provider_subject ON access_external_identity (provider, external_id)');
        $this->addSql('CREATE TABLE access_mobile_pending_auth (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, purpose VARCHAR(255) NOT NULL, device_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8FFA9CA4B3BC57DA ON access_mobile_pending_auth (token_hash)');
        $this->addSql('CREATE INDEX IDX_8FFA9CA4A76ED395 ON access_mobile_pending_auth (user_id)');
        $this->addSql('CREATE TABLE access_mobile_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id VARCHAR(64) NOT NULL, access_token_hash VARCHAR(64) NOT NULL, refresh_token_hash VARCHAR(64) NOT NULL, previous_refresh_token_hash VARCHAR(64) DEFAULT NULL, device_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, access_expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, refresh_expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, refresh_reuse_detected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C75F29C613FECDF ON access_mobile_session (session_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C75F29C9982CF5B ON access_mobile_session (access_token_hash)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C75F29C7288F9EC ON access_mobile_session (refresh_token_hash)');
        $this->addSql('CREATE INDEX IDX_C75F29CA76ED395 ON access_mobile_session (user_id)');
        $this->addSql('CREATE TABLE access_passkey_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, challenge_hash VARCHAR(64) NOT NULL, purpose VARCHAR(32) NOT NULL, relying_party_id VARCHAR(255) NOT NULL, origin VARCHAR(2048) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_access_passkey_challenge_hash ON access_passkey_challenge (challenge_hash)');
        $this->addSql('CREATE INDEX IDX_102C6BEFA76ED395 ON access_passkey_challenge (user_id)');
        $this->addSql('CREATE TABLE access_passkey_credential (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, credential_id VARCHAR(1024) NOT NULL, user_handle VARCHAR(255) NOT NULL, public_key TEXT NOT NULL, credential_record TEXT DEFAULT NULL, transports JSON NOT NULL, sign_count INT NOT NULL, name VARCHAR(120) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_access_passkey_credential_id ON access_passkey_credential (credential_id)');
        $this->addSql('CREATE INDEX IDX_2961A622A76ED395 ON access_passkey_credential (user_id)');
        $this->addSql('CREATE TABLE access_recovery_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_hash VARCHAR(255) NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_access_recovery_code_consumed_at ON access_recovery_code (consumed_at)');
        $this->addSql('CREATE INDEX IDX_B48369A0A76ED395 ON access_recovery_code (user_id)');
        $this->addSql('CREATE TABLE access_reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE9DFDA2A76ED395 ON access_reset_password_request (user_id)');
        $this->addSql('CREATE TABLE access_second_factor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, secret VARCHAR(128) NOT NULL, label VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8008AEBAA76ED395 ON access_second_factor (user_id)');
        $this->addSql('CREATE TABLE access_security_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(64) NOT NULL, context JSON NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_access_security_event_type ON access_security_event (event_type)');
        $this->addSql('CREATE INDEX idx_access_security_event_occurred_at ON access_security_event (occurred_at)');
        $this->addSql('CREATE INDEX IDX_EB8903B0A76ED395 ON access_security_event (user_id)');
        $this->addSql('CREATE TABLE access_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_identifier VARCHAR(128) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, trusted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18610FC197B88831 ON access_session (session_identifier)');
        $this->addSql('CREATE INDEX idx_access_session_expires_at ON access_session (expires_at)');
        $this->addSql('CREATE INDEX idx_access_session_revoked_at ON access_session (revoked_at)');
        $this->addSql('CREATE INDEX IDX_18610FC1A76ED395 ON access_session (user_id)');
        $this->addSql('CREATE TABLE access_verification_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, channel_type VARCHAR(32) NOT NULL, token VARCHAR(255) NOT NULL, target VARCHAR(255) NOT NULL, completed BOOLEAN NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, attempt_count INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_access_verification_challenge_type ON access_verification_challenge (channel_type)');
        $this->addSql('CREATE INDEX idx_access_verification_challenge_expires_at ON access_verification_challenge (expires_at)');
        $this->addSql('CREATE INDEX IDX_DD12BEB9A76ED395 ON access_verification_challenge (user_id)');
        $this->addSql('ALTER TABLE access_credential ADD CONSTRAINT FK_2F4185CAA76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_external_identity ADD CONSTRAINT FK_8B5367E2A76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_mobile_pending_auth ADD CONSTRAINT FK_8FFA9CA4A76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_mobile_session ADD CONSTRAINT FK_C75F29CA76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_passkey_challenge ADD CONSTRAINT FK_102C6BEFA76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_passkey_credential ADD CONSTRAINT FK_2961A622A76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_recovery_code ADD CONSTRAINT FK_B48369A0A76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_reset_password_request ADD CONSTRAINT FK_FE9DFDA2A76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_second_factor ADD CONSTRAINT FK_8008AEBAA76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_security_event ADD CONSTRAINT FK_EB8903B0A76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_session ADD CONSTRAINT FK_18610FC1A76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_verification_challenge ADD CONSTRAINT FK_DD12BEB9A76ED395 FOREIGN KEY (user_id) REFERENCES access (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Accessing data migrations require PostgreSQL.');
        $this->addSql('ALTER TABLE access_credential DROP CONSTRAINT FK_2F4185CAA76ED395');
        $this->addSql('ALTER TABLE access_external_identity DROP CONSTRAINT FK_8B5367E2A76ED395');
        $this->addSql('ALTER TABLE access_mobile_pending_auth DROP CONSTRAINT FK_8FFA9CA4A76ED395');
        $this->addSql('ALTER TABLE access_mobile_session DROP CONSTRAINT FK_C75F29CA76ED395');
        $this->addSql('ALTER TABLE access_passkey_challenge DROP CONSTRAINT FK_102C6BEFA76ED395');
        $this->addSql('ALTER TABLE access_passkey_credential DROP CONSTRAINT FK_2961A622A76ED395');
        $this->addSql('ALTER TABLE access_recovery_code DROP CONSTRAINT FK_B48369A0A76ED395');
        $this->addSql('ALTER TABLE access_reset_password_request DROP CONSTRAINT FK_FE9DFDA2A76ED395');
        $this->addSql('ALTER TABLE access_second_factor DROP CONSTRAINT FK_8008AEBAA76ED395');
        $this->addSql('ALTER TABLE access_security_event DROP CONSTRAINT FK_EB8903B0A76ED395');
        $this->addSql('ALTER TABLE access_session DROP CONSTRAINT FK_18610FC1A76ED395');
        $this->addSql('ALTER TABLE access_verification_challenge DROP CONSTRAINT FK_DD12BEB9A76ED395');
        $this->addSql('DROP TABLE access_credential');
        $this->addSql('DROP TABLE access');
        $this->addSql('DROP TABLE access_external_identity');
        $this->addSql('DROP TABLE access_mobile_pending_auth');
        $this->addSql('DROP TABLE access_mobile_session');
        $this->addSql('DROP TABLE access_passkey_challenge');
        $this->addSql('DROP TABLE access_passkey_credential');
        $this->addSql('DROP TABLE access_recovery_code');
        $this->addSql('DROP TABLE access_reset_password_request');
        $this->addSql('DROP TABLE access_second_factor');
        $this->addSql('DROP TABLE access_security_event');
        $this->addSql('DROP TABLE access_session');
        $this->addSql('DROP TABLE access_verification_challenge');
    }
}
