services:
  App\Accessing\ServiceInterface\AccessAuthenticationServiceInterface:
    alias: App\Accessing\Service\AccessAuthenticationService
    public: true

  App\Accessing\ServiceInterface\AccessRegistrationServiceInterface:
    alias: App\Accessing\Service\AccessRegistrationService
    public: true
