accessing_mailer_sender: no-reply@example.test
accessing_phone_verification_provider: fake
accessing_session_max_idle_days: 30
accessing_recovery_code_ttl_minutes: 30
accessing_verification_code_ttl_minutes: 10
accessing_user_lock_threshold: 5
accessing_user_lock_minutes: 15
